# Generated by Django 2.0.8 on 2018-12-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitecategory',
            name='count',
        ),
    ]
