# Generated by Django 2.1.4 on 2018-12-05 17:29

from django.db import migrations
import django_counter_field_py3.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecategory',
            name='count',
            field=django_counter_field_py3.fields.CounterField(default=0),
        ),
    ]
