# Generated by Django 2.1.4 on 2018-12-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20181205_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitecategory',
            name='count',
        ),
    ]
